import Foundation
import UIKit

/// Generates the donor medication-transfer form as a PDF for e-signature/printing.
/// This is a generic transfer record; a production build would swap in the exact
/// liability-release template required by the destination state/repository.
struct DonationFormGenerator {

    struct DonorInfo {
        var donorName: String
        var stateCode: String
        var date: Date = Date()
    }

    func makePDF(medication: Medication, donor: DonorInfo) -> URL? {
        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792) // US Letter @72dpi
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("Rxconcile-DonationForm-\(UUID().uuidString.prefix(8)).pdf")

        do {
            try renderer.writePDF(to: url) { ctx in
                ctx.beginPage()
                var y: CGFloat = 56
                let left: CGFloat = 56

                func draw(_ text: String, font: UIFont, gap: CGFloat = 8) {
                    let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: UIColor.black]
                    let bounding = (text as NSString).boundingRect(
                        with: CGSize(width: pageRect.width - left * 2, height: .greatestFiniteMagnitude),
                        options: [.usesLineFragmentOrigin, .usesFontLeading], attributes: attrs, context: nil)
                    (text as NSString).draw(with: CGRect(x: left, y: y, width: pageRect.width - left * 2, height: bounding.height),
                                            options: [.usesLineFragmentOrigin, .usesFontLeading], attributes: attrs, context: nil)
                    y += bounding.height + gap
                }

                draw("Medication Donation Transfer Form", font: .boldSystemFont(ofSize: 22), gap: 4)
                draw("Generated by Rxconcile • \(donor.date.formatted(date: .long, time: .omitted))",
                     font: .systemFont(ofSize: 11), gap: 20)

                draw("Donor", font: .boldSystemFont(ofSize: 15))
                draw("Name: \(donor.donorName.isEmpty ? "________________________" : donor.donorName)", font: .systemFont(ofSize: 13))
                draw("State: \(donor.stateCode)", font: .systemFont(ofSize: 13), gap: 20)

                draw("Medication being transferred for licensed review", font: .boldSystemFont(ofSize: 15))
                draw("Name: \(medication.name)", font: .systemFont(ofSize: 13))
                draw("Dosage: \(medication.dosage)", font: .systemFont(ofSize: 13))
                draw("NDC: \(medication.ndc ?? "—")", font: .systemFont(ofSize: 13))
                draw("Packaging: \(medication.form.rawValue)", font: .systemFont(ofSize: 13))
                draw("Quantity: \(medication.quantityRemaining)", font: .systemFont(ofSize: 13))
                let exp = medication.expirationDate?.formatted(date: .abbreviated, time: .omitted) ?? "—"
                draw("Expiration: \(exp)", font: .systemFont(ofSize: 13), gap: 24)

                draw("Attestation", font: .boldSystemFont(ofSize: 15))
                draw("I attest that this medication has been stored properly, is in its original "
                     + "tamper-evident packaging, is not a controlled substance, and is being "
                     + "transferred to a licensed repository or charitable pharmacy for eligibility "
                     + "review. I understand Rxconcile does not facilitate person-to-person drug "
                     + "transfer and that final acceptance is determined by a licensed pharmacist.",
                     font: .systemFont(ofSize: 12), gap: 40)

                draw("Donor signature: ______________________________   Date: ______________",
                     font: .systemFont(ofSize: 13), gap: 24)
                draw("Receiving pharmacist: _________________________   Date: ______________",
                     font: .systemFont(ofSize: 13))
            }
            return url
        } catch {
            return nil
        }
    }
}
